#!/usr/bin/env bash
# Script that installs Nginx server
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo service nginx start
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart