#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i '37i\rewrite ^/redirect_me https://github.com/Samaybyte/ permanent;' /etc/nginx/sites-available/default
service nginx start